//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentGeneration.LoggingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogType", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Logging")]
    public enum LogType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INFO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WARNING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Logging")]
    public enum Source : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATA_SERVICE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_GENERATION_SERVICE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BANK_RECORD_CARRIER_SERVICE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUTHENTICATION_SERVICE = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SHORTCODE", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Logging")]
    public enum SHORTCODE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EX = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AU = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DG = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Logging")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExeptionMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExeptionMsg {
            get {
                return this.ExeptionMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ExeptionMsgField, value) != true)) {
                    this.ExeptionMsgField = value;
                    this.RaisePropertyChanged("ExeptionMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMsg {
            get {
                return this.ResponseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMsgField, value) != true)) {
                    this.ResponseMsgField = value;
                    this.RaisePropertyChanged("ResponseMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ENVIRONMENT", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Logging")]
    public enum ENVIRONMENT : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WBD = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AK_SHARED_SERVICES = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoggingService.ILogging")]
    public interface ILogging {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogging/log", ReplyAction="http://tempuri.org/ILogging/logResponse")]
        DocumentGeneration.LoggingService.Response log(DocumentGeneration.LoggingService.LogType logType, DocumentGeneration.LoggingService.Source source, DocumentGeneration.LoggingService.SHORTCODE shortcode, int userid, string dl_nr, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogging/logWithEnvironment", ReplyAction="http://tempuri.org/ILogging/logWithEnvironmentResponse")]
        DocumentGeneration.LoggingService.Response logWithEnvironment(DocumentGeneration.LoggingService.LogType logType, DocumentGeneration.LoggingService.Source source, DocumentGeneration.LoggingService.SHORTCODE shortcode, int userid, string dl_nr, string msg, DocumentGeneration.LoggingService.ENVIRONMENT env);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoggingChannel : DocumentGeneration.LoggingService.ILogging, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggingClient : System.ServiceModel.ClientBase<DocumentGeneration.LoggingService.ILogging>, DocumentGeneration.LoggingService.ILogging {
        
        public LoggingClient() {
        }
        
        public LoggingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DocumentGeneration.LoggingService.Response log(DocumentGeneration.LoggingService.LogType logType, DocumentGeneration.LoggingService.Source source, DocumentGeneration.LoggingService.SHORTCODE shortcode, int userid, string dl_nr, string msg) {
            return base.Channel.log(logType, source, shortcode, userid, dl_nr, msg);
        }
        
        public DocumentGeneration.LoggingService.Response logWithEnvironment(DocumentGeneration.LoggingService.LogType logType, DocumentGeneration.LoggingService.Source source, DocumentGeneration.LoggingService.SHORTCODE shortcode, int userid, string dl_nr, string msg, DocumentGeneration.LoggingService.ENVIRONMENT env) {
            return base.Channel.logWithEnvironment(logType, source, shortcode, userid, dl_nr, msg, env);
        }
    }
}
