//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentGeneration.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Authentication")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExeptionMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExeptionMsg {
            get {
                return this.ExeptionMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ExeptionMsgField, value) != true)) {
                    this.ExeptionMsgField = value;
                    this.RaisePropertyChanged("ExeptionMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMsg {
            get {
                return this.ResponseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMsgField, value) != true)) {
                    this.ResponseMsgField = value;
                    this.RaisePropertyChanged("ResponseMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Authentication")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUsedTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DocumentGeneration.AuthService.User SessionUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUsedTimestamp {
            get {
                return this.LastUsedTimestampField;
            }
            set {
                if ((this.LastUsedTimestampField.Equals(value) != true)) {
                    this.LastUsedTimestampField = value;
                    this.RaisePropertyChanged("LastUsedTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DocumentGeneration.AuthService.User SessionUser {
            get {
                return this.SessionUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionUserField, value) != true)) {
                    this.SessionUserField = value;
                    this.RaisePropertyChanged("SessionUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                if ((this.isValidField.Equals(value) != true)) {
                    this.isValidField = value;
                    this.RaisePropertyChanged("isValid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.Authentication")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanWriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsANFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PvsPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PvsUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DocumentGeneration.AuthService.KeyValuePairOfstringstring[] SettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanRead {
            get {
                return this.CanReadField;
            }
            set {
                if ((this.CanReadField.Equals(value) != true)) {
                    this.CanReadField = value;
                    this.RaisePropertyChanged("CanRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanReport {
            get {
                return this.CanReportField;
            }
            set {
                if ((this.CanReportField.Equals(value) != true)) {
                    this.CanReportField = value;
                    this.RaisePropertyChanged("CanReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanWrite {
            get {
                return this.CanWriteField;
            }
            set {
                if ((this.CanWriteField.Equals(value) != true)) {
                    this.CanWriteField = value;
                    this.RaisePropertyChanged("CanWrite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsANF {
            get {
                return this.IsANFField;
            }
            set {
                if ((this.IsANFField.Equals(value) != true)) {
                    this.IsANFField = value;
                    this.RaisePropertyChanged("IsANF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWBD {
            get {
                return this.IsWBDField;
            }
            set {
                if ((this.IsWBDField.Equals(value) != true)) {
                    this.IsWBDField = value;
                    this.RaisePropertyChanged("IsWBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PvsPassword {
            get {
                return this.PvsPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PvsPasswordField, value) != true)) {
                    this.PvsPasswordField = value;
                    this.RaisePropertyChanged("PvsPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PvsUsername {
            get {
                return this.PvsUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PvsUsernameField, value) != true)) {
                    this.PvsUsernameField = value;
                    this.RaisePropertyChanged("PvsUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DocumentGeneration.AuthService.KeyValuePairOfstringstring[] Settings {
            get {
                return this.SettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsField, value) != true)) {
                    this.SettingsField = value;
                    this.RaisePropertyChanged("Settings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shortname {
            get {
                return this.ShortnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortnameField, value) != true)) {
                    this.ShortnameField = value;
                    this.RaisePropertyChanged("Shortname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringstring", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    [System.SerializableAttribute()]
    public partial struct KeyValuePairOfstringstring : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string keyField;
        
        private string valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getAllSessions", ReplyAction="http://tempuri.org/IAuthService/getAllSessionsResponse")]
        DocumentGeneration.AuthService.Response getAllSessions(out DocumentGeneration.AuthService.Session[] sessions, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getUserById", ReplyAction="http://tempuri.org/IAuthService/getUserByIdResponse")]
        DocumentGeneration.AuthService.Response getUserById(out DocumentGeneration.AuthService.User user, string token, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/doLogin", ReplyAction="http://tempuri.org/IAuthService/doLoginResponse")]
        DocumentGeneration.AuthService.Response doLogin(out string token, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/doSSOLogin", ReplyAction="http://tempuri.org/IAuthService/doSSOLoginResponse")]
        DocumentGeneration.AuthService.Response doSSOLogin(out string token, string adAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getUser", ReplyAction="http://tempuri.org/IAuthService/getUserResponse")]
        DocumentGeneration.AuthService.Response getUser(out DocumentGeneration.AuthService.User user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getSetting", ReplyAction="http://tempuri.org/IAuthService/getSettingResponse")]
        DocumentGeneration.AuthService.Response getSetting(out string setting, string key, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getAllUsers", ReplyAction="http://tempuri.org/IAuthService/getAllUsersResponse")]
        DocumentGeneration.AuthService.Response getAllUsers(out DocumentGeneration.AuthService.User[] users, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/setPassword", ReplyAction="http://tempuri.org/IAuthService/setPasswordResponse")]
        DocumentGeneration.AuthService.Response setPassword(string token, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/updateUser", ReplyAction="http://tempuri.org/IAuthService/updateUserResponse")]
        DocumentGeneration.AuthService.Response updateUser(string token, DocumentGeneration.AuthService.User user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/insertUser", ReplyAction="http://tempuri.org/IAuthService/insertUserResponse")]
        DocumentGeneration.AuthService.Response insertUser(string token, DocumentGeneration.AuthService.User user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getAllSignatures", ReplyAction="http://tempuri.org/IAuthService/getAllSignaturesResponse")]
        DocumentGeneration.AuthService.Response getAllSignatures(out string[] signatures, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/getSignature", ReplyAction="http://tempuri.org/IAuthService/getSignatureResponse")]
        DocumentGeneration.AuthService.Response getSignature(out string content, out int length, string token, string name, int fromIndex, int packagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/saveSignature", ReplyAction="http://tempuri.org/IAuthService/saveSignatureResponse")]
        DocumentGeneration.AuthService.Response saveSignature(string token, string transferid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/startSignatureTransfer", ReplyAction="http://tempuri.org/IAuthService/startSignatureTransferResponse")]
        DocumentGeneration.AuthService.Response startSignatureTransfer(out string transferid, string token, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/transferSignatureData", ReplyAction="http://tempuri.org/IAuthService/transferSignatureDataResponse")]
        DocumentGeneration.AuthService.Response transferSignatureData(string token, string transferid, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/doLoginWithApp", ReplyAction="http://tempuri.org/IAuthService/doLoginWithAppResponse")]
        DocumentGeneration.AuthService.Response doLoginWithApp(out string token, string username, string password, bool appIsAnf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/doSSOLoginWithApp", ReplyAction="http://tempuri.org/IAuthService/doSSOLoginWithAppResponse")]
        DocumentGeneration.AuthService.Response doSSOLoginWithApp(out string token, string adAccount, bool appIsAnf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/searchProtocolByEmployee", ReplyAction="http://tempuri.org/IAuthService/searchProtocolByEmployeeResponse")]
        string[][] searchProtocolByEmployee(string username, bool searchwbd, string dateRestriction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/searchProtocolByRequestID", ReplyAction="http://tempuri.org/IAuthService/searchProtocolByRequestIDResponse")]
        string[][] searchProtocolByRequestID(string requestID, bool searchwbd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/searchProtocolByCustomer", ReplyAction="http://tempuri.org/IAuthService/searchProtocolByCustomerResponse")]
        string[][] searchProtocolByCustomer(string firstname, string lastname, string birthdate, bool searchwbd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : DocumentGeneration.AuthService.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<DocumentGeneration.AuthService.IAuthService>, DocumentGeneration.AuthService.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DocumentGeneration.AuthService.Response getAllSessions(out DocumentGeneration.AuthService.Session[] sessions, string token) {
            return base.Channel.getAllSessions(out sessions, token);
        }
        
        public DocumentGeneration.AuthService.Response getUserById(out DocumentGeneration.AuthService.User user, string token, int id) {
            return base.Channel.getUserById(out user, token, id);
        }
        
        public DocumentGeneration.AuthService.Response doLogin(out string token, string username, string password) {
            return base.Channel.doLogin(out token, username, password);
        }
        
        public DocumentGeneration.AuthService.Response doSSOLogin(out string token, string adAccount) {
            return base.Channel.doSSOLogin(out token, adAccount);
        }
        
        public DocumentGeneration.AuthService.Response getUser(out DocumentGeneration.AuthService.User user, string token) {
            return base.Channel.getUser(out user, token);
        }
        
        public DocumentGeneration.AuthService.Response getSetting(out string setting, string key, string token) {
            return base.Channel.getSetting(out setting, key, token);
        }
        
        public DocumentGeneration.AuthService.Response getAllUsers(out DocumentGeneration.AuthService.User[] users, string token) {
            return base.Channel.getAllUsers(out users, token);
        }
        
        public DocumentGeneration.AuthService.Response setPassword(string token, string password) {
            return base.Channel.setPassword(token, password);
        }
        
        public DocumentGeneration.AuthService.Response updateUser(string token, DocumentGeneration.AuthService.User user, string password) {
            return base.Channel.updateUser(token, user, password);
        }
        
        public DocumentGeneration.AuthService.Response insertUser(string token, DocumentGeneration.AuthService.User user, string password) {
            return base.Channel.insertUser(token, user, password);
        }
        
        public DocumentGeneration.AuthService.Response getAllSignatures(out string[] signatures, string token) {
            return base.Channel.getAllSignatures(out signatures, token);
        }
        
        public DocumentGeneration.AuthService.Response getSignature(out string content, out int length, string token, string name, int fromIndex, int packagesize) {
            return base.Channel.getSignature(out content, out length, token, name, fromIndex, packagesize);
        }
        
        public DocumentGeneration.AuthService.Response saveSignature(string token, string transferid) {
            return base.Channel.saveSignature(token, transferid);
        }
        
        public DocumentGeneration.AuthService.Response startSignatureTransfer(out string transferid, string token, string name) {
            return base.Channel.startSignatureTransfer(out transferid, token, name);
        }
        
        public DocumentGeneration.AuthService.Response transferSignatureData(string token, string transferid, string content) {
            return base.Channel.transferSignatureData(token, transferid, content);
        }
        
        public DocumentGeneration.AuthService.Response doLoginWithApp(out string token, string username, string password, bool appIsAnf) {
            return base.Channel.doLoginWithApp(out token, username, password, appIsAnf);
        }
        
        public DocumentGeneration.AuthService.Response doSSOLoginWithApp(out string token, string adAccount, bool appIsAnf) {
            return base.Channel.doSSOLoginWithApp(out token, adAccount, appIsAnf);
        }
        
        public string[][] searchProtocolByEmployee(string username, bool searchwbd, string dateRestriction) {
            return base.Channel.searchProtocolByEmployee(username, searchwbd, dateRestriction);
        }
        
        public string[][] searchProtocolByRequestID(string requestID, bool searchwbd) {
            return base.Channel.searchProtocolByRequestID(requestID, searchwbd);
        }
        
        public string[][] searchProtocolByCustomer(string firstname, string lastname, string birthdate, bool searchwbd) {
            return base.Channel.searchProtocolByCustomer(firstname, lastname, birthdate, searchwbd);
        }
    }
}
